name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: sonarscan-dotnet
      uses: highbyte/sonarscan-dotnet@v2.1.1-beta
      with:
        sonarProjectKey: 210628-UTA-NET-Caleb-Huss-P1
        sonarProjectName: Caleb-Huss-P1
        sonarOrganization: 210628-uta-net
        dotnetDisableTests: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: dotnet publish --configuration Release -o ./publish
    - name: deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: CalebsRootBeerEmpire
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
        package: ./publish
